[features]
seeds = false
[programs.devnet]
soltreasure = "8oLQrC9nJo7NkEZtAoGgsdXWLPWuPycqwwYbadV5ELXW"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/you/home/directory/.config/solana/id.json"

[scripts]
test = "node tests/soltreasure.js"
