[features]
seeds = false
[programs.devnet]
buymeasolcoffee = "HMJb3LsZb6NQUb1HkBSHMp1YgC8JDBwgSw1YAaMBdanr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/drkrueger/.config/solana/id.json"

[scripts]
test = "node tests/buymeasolcoffee.js"